#Los comentarios que pongamos en este archivo no pueden tener acentos o da error al compilar
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registro_usuarios?createDatabaseIfNotExist=true #conexion a la bbdd en el puerto 3306 y la bbdd es mydb
    username: root
    password: root
  jpa:
    show-sql: true #para mostrar el sql en pantalla a medida que se realizan las consultas en el log
    hibernate:
      ddl-auto: update #Cuando arranquemos el servidor mira los campos de las clases y si eliminamos uno lo elimina en la bbdd
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-circular-references: true #para solucionar un error cuando cambio la BBDD con las tablas relacionadas de uno a muchos
server:
  port: 8081